### PR TITLE
PS-2618 Use staging/live env configuration by default (production)

### PR DESCRIPTION
**Pull request by odokienko**
- Developer(s): @odokienko

- Ticket: https://spryker.atlassian.net/browse/PS-2618

- Academy PR: ACADEMY_URL_HERE

- Release Group: https://release.spryker.com/release-groups/view/1041

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   Install               | patch  |   |

#### Release Notes

There was the 'development' environment used by default. That ran development installation, which dropped DB, removed schema files etc. It was a huge danger if anyone would run it on production or another environment. This fix makes 'production' environment as default that eliminates this danger.

-----------------------------------------

##### Change log

Improvements

- Added `public` access modifier for class constants.
- Updated behavior of `InstallConsoleCommand::getEnvironment()` so when no `APPLICATION_ENV` env variable is set, the default value will be 'production'. It is done for security reasons.

### CODE REVIEW

**Comment by dereuromark** [comment]
Is this a 0.6 release?
Please create a template here then as the standalone releasing will need this.

**Comment by dereuromark** [comment]
I was thinking about this: As this just introduces a safer default for production, we probably shouldnt do a major jump (0.x), but a patch release (0.5.1), right?

**Comment by gerner-spryker** [comment]
@stereomon What's your opinion on the minor/patch question?

**Comment by stereomon** [comment]
I also think that we can make a patch here.

**Comment by odokienko** [comment]
updated to `patch`

**Comment by dereuromark** [comment]
Please remove invalid things from Constraint Updates and never fill it unless you know what you are doing!

**Pull request merged**
